from django.db import models

# Create your models here.
class Today12(models.Model):
    month = models.IntegerField()
    day = models.IntegerField()
    one_total = models.CharField(max_length=300)
    one_year_1 = models.CharField(max_length=100)
    one_year_2 = models.CharField(max_length=100)
    one_year_3 = models.CharField(max_length=100)
    one_year_4 = models.CharField(max_length=100)
    one_year_5 = models.CharField(max_length=100)
    two_total = models.CharField(max_length=300)
    two_year_1 = models.CharField(max_length=100)
    two_year_2 = models.CharField(max_length=100)
    two_year_3 = models.CharField(max_length=100)
    two_year_4 = models.CharField(max_length=100)
    two_year_5 = models.CharField(max_length=100)
    three_total = models.CharField(max_length=300)
    three_year_1 = models.CharField(max_length=100)
    three_year_2 = models.CharField(max_length=100)
    three_year_3 = models.CharField(max_length=100)
    three_year_4 = models.CharField(max_length=100)
    three_year_5 = models.CharField(max_length=100)
    four_total = models.CharField(max_length=300)
    four_year_1 = models.CharField(max_length=100)
    four_year_2 = models.CharField(max_length=100)
    four_year_3 = models.CharField(max_length=100)
    four_year_4 = models.CharField(max_length=100)
    four_year_5 = models.CharField(max_length=100)
    five_total = models.CharField(max_length=300)
    five_year_1 = models.CharField(max_length=100)
    five_year_2 = models.CharField(max_length=100)
    five_year_3 = models.CharField(max_length=100)
    five_year_4 = models.CharField(max_length=100)
    five_year_5 = models.CharField(max_length=100)
    six_total = models.CharField(max_length=300)
    six_year_1 = models.CharField(max_length=100)
    six_year_2 = models.CharField(max_length=100)
    six_year_3 = models.CharField(max_length=100)
    six_year_4 = models.CharField(max_length=100)
    six_year_5 = models.CharField(max_length=100)
    seven_total = models.CharField(max_length=300)
    seven_year_1 = models.CharField(max_length=100)
    seven_year_2 = models.CharField(max_length=100)
    seven_year_3 = models.CharField(max_length=100)
    seven_year_4 = models.CharField(max_length=100)
    seven_year_5 = models.CharField(max_length=100)
    eight_total = models.CharField(max_length=300)
    eight_year_1 = models.CharField(max_length=100)
    eight_year_2 = models.CharField(max_length=100)
    eight_year_3 = models.CharField(max_length=100)
    eight_year_4 = models.CharField(max_length=100)
    eight_year_5 = models.CharField(max_length=100)
    nine_total = models.CharField(max_length=300)
    nine_year_1 = models.CharField(max_length=100)
    nine_year_2 = models.CharField(max_length=100)
    nine_year_3 = models.CharField(max_length=100)
    nine_year_4 = models.CharField(max_length=100)
    nine_year_5 = models.CharField(max_length=100)
    ten_total = models.CharField(max_length=300)
    ten_year_1 = models.CharField(max_length=100)
    ten_year_2 = models.CharField(max_length=100)
    ten_year_3 = models.CharField(max_length=100)
    ten_year_4 = models.CharField(max_length=100)
    ten_year_5 = models.CharField(max_length=100)
    eleven_total = models.CharField(max_length=300)
    eleven_year_1 = models.CharField(max_length=100)
    eleven_year_2 = models.CharField(max_length=100)
    eleven_year_3 = models.CharField(max_length=100)
    eleven_year_4 = models.CharField(max_length=100)
    eleven_year_5 = models.CharField(max_length=100)
    twelve_total = models.CharField(max_length=300)
    twelve_year_1 = models.CharField(max_length=100)
    twelve_year_2 = models.CharField(max_length=100)
    twelve_year_3 = models.CharField(max_length=100)
    twelve_year_4 = models.CharField(max_length=100)
    twelve_year_5 = models.CharField(max_length=100)

    class Meta:
        ordering = ['-month','-day']


    def __str__(self):
        return self.pk, self.month, self.day, self.one_total
